### ISSUE TITLE
What is difference between `client.query` and `client.readQuery`?

### ISSUE THREAD

**Issue by barbalex** [apollographql/apollo-link-state#106]
In the readme both are used:

- `client.query` in: `const initial = await client.query({ query });`
- `client.readQuery` in `const current = client.readQuery({ query, variables });`

Also: Why is one awaited and the other not?

I'm a bit afraid that I am outing myself as a horrendous noob here :-|

**Comment by ntkoso** [comment]
Look here [readQuery API](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-cache-inmemory#readquery) 
Instead of trying to fetch missing data from server it will throw an error.
If query only has `@client` fields you can avoid Promise initialization and just access cache data.

**Comment by barbalex** [comment]
Thanks.

The fact that readQuery is synchronous is important to know but does not seem obvious from reading the docs.

I am not 100% sure what makes a query synchronous though aus you mention `@client`:

- is every `readQuery` call synchronous?
- is every `query` call synchronous as long as it decides to fetch the data from cache?
- is every `query` and `readQuery` call synchronous as long as they only query `@client` fields?

And why would you use `query` to call `@client` fields? Why not use `readQuery`? In the readme example the call to `query` only calls `@client` fields.

 Would one use `query` to be able to combine calling data from server and client in one single query?

I also had a weird problem where adding `@client` fields to a regular query (called using `graphql` and `gql`) made that query not work (though without an error - data did simply not appear). I had to use a separate `graphql` call to add the `@client` fields to the component (naming the data prop to enable this). But this is a separate issue I may come back to later.

**Comment by ntkoso** [comment]
@barbalex Every `readQuery` call is synchronous. From API standpoint `query` is always asynchronous because you need to `await` returned Promise.
Reason for using `query` instead of `readQuery` is that first call to `query` writes initial state into cache. Before first `query` cache is empty and `readQuery` calls will throw.
As for combined client and server data, read [advanced tests](https://github.com/apollographql/apollo-link-state/blob/master/src/__tests__/advanced.ts)
If you have this type of questions it's a good idea to read test files of the projects. Typically tests use small and concise parts of the API and you can see examples of different scenarios.

**Comment by barbalex** [comment]
Thanks, that was very helpful!
