### ISSUE TITLE
can I read or write to local state in downstream chain?

### ISSUE THREAD

**Issue by yeoberg88** [apollographql/apollo-link-state#112]
As subject, says i need to send request base on some local state.

Many thanks.

**Comment by jbaxleyiii** [comment]
@yeoberg88 could you provide an example of what you are trying to accomplish?

**Comment by yeoberg88** [comment]
@jbaxleyiii Of course. Many thanks

I use React, React-router v4 and AWS Cognito to do Authentication. 

Down the chain, i need to refresh the token if is expired.
```js
const link = APolloLink.from([
	stateLink,
	refreshLink,
	httpLink
])
```
I created an callback Route component to obtain tokens from the Authenication Server.

After obtain the tokens, I would like to 'dispatch' the token to the 'store', the 'store' will have the following shape. (I can store in local storage, but i prefer to store in memory if it is possible)
```js
{
	username: xxx
	idToken: xxxx
	accessToken: xxxx
	refreshToken: xxx
}
```

In the refreshLink, it would be great if I can read the local state to decide if refreshing token is required or change the username to null if refreshing token is failed.

As a result, components which are watching the query can react accordingly. (route to home page if username === null)

**Comment by goldenbearkin** [comment]
I also ask the same question in the apollo-link repor. 
https://github.com/apollographql/apollo-link/issues/272. Below is the recap.

Can I access cache in the link chain? 
below snippet explains my intention.
```js
new ApolloLink((operation, forward) => {
    const me = client.readQuery({
      query: gql`
          query meQuery {
            Me @client {
              name
              age
            }
          }
        `
    });
    console.log(me);
    return forward!(operation);
  }),
```
RM: I just make up the client object follow the Direct Cache Access section of the Apollo client's doc.

Why do I want to access the cache in the link chain?
Let say I need to refresh the idToken if it's expired, the refresh token logic should be done before the httpLink so that I can attach an non-expired token in the header. Also, if the refresh token process failed, I need to change the local state (apollo-link-state) sequentially and those components who is watching the local state can react upon the change.

**Comment by jbaxleyiii** [comment]
@yeoberg88 @goldenbearkin ah I think I understand! One of the ways we designed Apollo Link was to serve more complex auth flows. So you can access the `cache` from within a link in order to read and write to it. 

```js
(operation, forward) => {
  const { cache } = operation.getContext();
  // cache.readQuery
  // cache.writeQuery
}
```

This lets you write and read from the cache to store login information. You could implement a method on your link class to reauthenticate and write to the cache when needed.

Does that make sense?

**Comment by yeoberg88** [comment]
Awesome. Thanks @jbaxleyiii
