### ISSUE TITLE
Add local state to Schema Documentation

### ISSUE THREAD

**Issue by kedarguy** [apollographql/apollo-link-state#116]
When adding a schema withClientState(), the new queries and mutations are not available in the schema documentation .

Is there a way to add schema support?

**Comment by happylinks** [comment]
I was also thinking about this! Would be cool if you could make a function that returns the introspection-json based on the withClientState object so you could inspect it with GraphiQL.
But maybe we're missing a real graphql schema for that?
Wouldn't it be possible to create the schema based on a real .gql file? Basically like this: http://graphql.org/graphql-js/#writing-code

**Comment by jbaxleyiii** [comment]
@kedarguy @happylinks if you want to use a full schema I'd check out [this link](https://www.apollographql.com/docs/link/links/schema.html)

I don't want to support a schema for this link because that means all of graphql-js is on the client. That's a pretty big bundle increase and this link exists to make the same rough functionality work without all the extra type system
