### ISSUE TITLE
Cannot read property kind on imported/external query, works with local query

### ISSUE THREAD

**Issue by pcjmfranken** [apollographql/apollo-link-state#145]
I'm getting the error `Uncaught (in promise) TypeError: Cannot read property 'kind' of undefined at checkDocument` when using an imported/external query in a resolver. The readQuery resolves fine when the query is declared inside the resolver and called from there.

### Error code
```js
// Either imported query
import { QUERY_MODAL } from './graphql'

// Or query declared outside resolver function in same file
const QUERY_MODAL = gql`
  query queryModal {
    modal @client { visible }
  }
`

const notificationResolvers: {
Mutation: {
      toggleModal: async (_, { visible }, { cache }) => {
        const current = cache.readQuery({ QUERY_MODAL })

        const data = {
          modal: {
            __typename: 'modal',
            visible: !current.modal.visible
          }
        }
        cache.writeData({ data })
        return data.modal
      }
    },
}
```
### Working code
It works fine without errors when the query is called from inside the resolver like in the examples.
```js
const notificationResolvers: {
Mutation: {
      toggleModal: async (_, { visible }, { cache }) => {
        // Internal query
        const query = gql`
          query queryModal {
            modal @client { visible }
          }
        `

        // Using internal query instead of external
        const current = cache.readQuery({ query })

        const data = {
          modal: {
            __typename: 'modal',
            visible: !current.modal.visible
          }
        }
        cache.writeData({ data })
        return data.modal
      }
    },
}
```

**Comment by steve-a-jones** [comment]
@pcjmfranken - I believe your latter example is working because you have named your `const` "`query`".. and when you pass it to `cache.readQuery` as `cache.readQuery({ query })` this is destructured as `cache.readQuery({query: query})` which satisfies the input object required by `cache.readQuery` (https://www.apollographql.com/docs/react/basics/caching.html#readquery). 

Your previous example is destructuring as `cache.readQuery({QUERY_MODAL: QUERY_MODAL})`  which is invalid input as a `query` property is needed on the input object.

**Comment by pcjmfranken** [comment]
That was indeed the problem, thanks @steve-a-jones!
