### ISSUE TITLE
Is the @client directive the best "consumer-side" API?

### ISSUE THREAD

**Issue by youknowriad** [apollographql/apollo-link-state#155]
First, thanks a lot for your work democratizing GraphQL technologies.

From an API point of view, a component declaring its data needs (or mutations) shouldn’t have to worry about the fact that the resolver is local or remote.

In that sense, I think, it would be better if the @client tag could be avoided. And replaced by some API on the resolver side instead. Often times, the resolver’s author is very different from the consumer.

Any thoughts about that? thank you.

**Context:** We're doing some explorations using GraphQL client-side in WordPress. The idea is that WordPress Plugins or WordPress Core "register" resolvers (clientSide or remote, doesn't matter), and a consumer (in general another plugin) can declare data needs. The plugin author writing the consumer side code is different from the one writing the resolvers (production side) and it would be great if we had one and unique way to access/mutate data (unique GraphiQL instance) without the need to worry about the `@client` directive.

**Comment by peggyrayzis** [comment]
Thanks for your feedback @youknowriad! Unfortunately, the `@client` directive is a necessity right now because we don't have any concept of a client-side schema. Without the directive and a schema, Apollo Link would have no way of knowing which data is remote and which data is local.

The reason we don't have a client-side schema is because the modules in `graphql-js` for constructing and validating against a schema would dramatically increase bundle size. This is the same reason why Apollo Client doesn't receive your entire schema from the server. In the future, we might explore some build-time tools to augment what Apollo Client receives from the server with your local data's types. Once that happens, we might be able to eliminate the `@client` directive.

**Comment by youknowriad** [comment]
Thanks for the answer. I understand the tradeoffs. I might try a custom solution using only Apollo link right now (no client), I'll see how it goes.

Anyway, look forward seeing how this evolves and thanks against for your work on these awesome tools. Feel free to close this issue if needed.

**Comment by peggyrayzis** [comment]
Nice! Keep us in the loop with what you build w/ Apollo Link, we would love to feature it on our [community links](https://www.apollographql.com/docs/link/links/community.html) page once it's ready 😀

I'm going to close this issue for now, but we can revisit once we have a client-side schema solution.
