### ISSUE TITLE
Link State complains when combining local and remote state

### ISSUE THREAD

**Issue by rotexhawk** [apollographql/apollo-link-state#265]
I am trying to combine local and remote state for a search page. The local state has the form fields and the remote data is added to the results field in the query below. 

I get this warning. I understand that the server doesn't have a form field but I am marking `form` with `@client` directive. Not sure why link-state is expecting the form field from the server. 

````
Missing field form in {
  "__typename": "Search",
  "results": [
    {
      "id": 77,
      "email": "Nayeli_Langworth@Jo
````

````javascript
import gql from "graphql-tag";

export const searchQuery = gql`
    query {
        search {
            form @client {
                sort
            }
            results {
                id
                email
                nicename
                thumbnail
                specialties
                tools
                reading_style
            }
        }
    }
`;
```` 

Here is the default state: 

````javascript
const defaults = {
    search: {
        __typename: "Search",
        form: {
            __typename: "form",
            sort: [
                "Available",
                "Busy",
                "Star Rating",
                "Alphabetical",
                "New",
                "Price-(Low to High)",
                "Price-(Hight to Low)"
            ],
        }
    }
};
````

**Comment by avin** [comment]
I think you have to use this query
```js
export const searchQuery = gql`
    query {
        search {
            results {
                id
                email
                nicename
                thumbnail
                specialties
                tools
                reading_style
            }
        }

        form @client {
            sort
        }
    }
`;
```

**Comment by kaanozcan** [comment]
I am having the same issue. 

We have two servers one responsible for rendering UI the other is a apollo-graphql server. 
So we get those config objects passed to our docker containers. Since apollo is responsible for resolving data for ssr and can pass the data to the browser (by serializing cache) I figured I can pass down the config object to the browser using apollo-link-state (and use it universally for ssr too) but the __typename errors causing the container to restart the moment I configure apollo-link-state with my data. My config object has no __typename in it since it's not provided by the graphql server. 

Anyway to get around this other than manually putting __typename in the config object?

**Comment by hwillson** [comment]
It sounds to me like you're attempting to access the `@client` based `form` field and selection set before it has been initialized in the cache. Setting a [default](https://www.apollographql.com/docs/link/links/state.html#defaults) for `form` should help address this.
