### ISSUE TITLE
Cache-only fetchPolicy results in 4x renders

### ISSUE THREAD

**Issue by pcmaffey** [apollographql/apollo-link-state#289]
Reproduction: add `fetchPolicy: 'cache-only'` to TodoList query in examples. Then console.log(todos)...

With default `cache-and-network`, the render function runs twice (with no changes to data, loading, or networkStatus).
With `cache-only`, it runs 4x (also with no changes). 

I would expect with cache only, it would render fewer times than cache-and-network.

**Comment by hwillson** [comment]
Thanks for reporting this @pcmaffey. We're working on a new version of `apollo-link-state` that helps minimize this a bit (down to 3 renders), but there is still an additional (and usually un-necessary) render happening that needs to be looked into further. The current render path (in React Apollo) looks like:

1. Constructor, then first render.
2. After first render, `componetDidMount` eventually (and intentionally) triggers a `forceUpdate`, which causes the second render.
3. After the second render, the observable setup via `startQuerySubscription` (from `componentDidMount`) still receives another round of data, which then leads to `forceUpdate` being called again, and another render (even though that incoming data hasn't changed since the last render).

This issue isn't caused by `apollo-link-state` however, and would be better reported in the [React Apollo](http://github.com/apollographql/react-apollo) repo. If you don't mind re-opening this issue over in the React Apollo repo, that would be great. Thanks!

**Comment by frederikhors** [comment]
@hwillson are you going to open it or maybe I open it for you?

**Comment by frederikhors** [comment]
@pcmaffey are you going to open it or maybe I open it for you?

**Comment by pcmaffey** [comment]
Am currently traveling - so feel free to go ahead and open it.
