### ISSUE TITLE
Async custom query resolvers

### ISSUE THREAD

**Issue by zouxuoz** [apollographql/apollo-link-state#311]
I’m trying to implement the resolver for local state query. If I understand correctly - it should be execute as sync query, but no matter what I do - it’s executed as async and the component wrapped with query rendered twice: with loading = true and with loading = false.

Repo with code: https://github.com/zouxuoz/apollo-local-example

```js
import React from 'react';
import ReactDOM from 'react-dom';
import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloLink } from 'apollo-link';
import { withClientState } from 'apollo-link-state';
import { ApolloProvider, Query } from 'react-apollo'; 
import gql from 'graphql-tag';

const cache = new InMemoryCache();

const stateLink = withClientState({
  cache,
  defaults: {
    common: 'common',
  },
  resolvers: {
    Query: {
      custom: () => 'custom',
    },
  },
});

const client = new ApolloClient({
  cache,
  link: ApolloLink.from([
    stateLink,
  ]),
});

const TEST_COMMON_QUERY = gql`
  query {
    common @client
  }
`;

const TEST_CUSTOM_QUERY = gql`
  query {
    custom @client
  }
`;

class Application extends React.Component {
  renderCommonContent = ({ loading, data }) => {
    console.log('renderCommonContent', loading, data);

    return loading ? 'Loading...' : data.common;
  };

  renderCustomContent = ({ loading, data }) => {
    console.log('renderCustomContent', loading, data);

    return loading ? 'Loading...' : data.custom;
  };

  render() {
    return (
      <div className="Application">
        <Query query={TEST_COMMON_QUERY}>
          {this.renderCommonContent}
        </Query>
        <Query query={TEST_CUSTOM_QUERY}>
          {this.renderCustomContent}
        </Query>
      </div>
    );
  }
}

ReactDOM.render((
  <ApolloProvider client={client}>
    <Application />
  </ApolloProvider>
), document.getElementById('root'));
```

**Comment by hwillson** [comment]
@zouxuoz This is normal behaviour. Your first `Query` component is pulling the result directly from the cache (that was written there using `defaults`). Because of this, the `Query` component never hits a loading state. Your second `Query` component doesn't find the result it's looking for in the cache, so it proceeds down the link chain with the data request. As far as your second `Query` component is concerned, a data request is being made and hasn't been fulfilled yet, which means your component is put into a loading state.

**Comment by adjourn** [comment]
@hwillson 2 renders is normal in any case? 

Here's a screenshot if I only query client data that has been populated with `defaults`.

![screenshot](https://user-images.githubusercontent.com/17890701/51417630-85c00680-1b87-11e9-9076-7ec0bf3d0fee.png)

**Comment by jalooc** [comment]
@adjourn In both logs loading is `false` and `data` is hydrated, so yeah - looks like it was synchronously derived from cache 👍.

There can be numerous reasons why it logs twice, it's hard to really say since you didn't post any information how you log this. The most probable reason for double logging is possibly your component  rerendering or just the `<Query>` component's render function being recalled (which is perfectly normal and you shouldn't be worried about it).

**Comment by adjourn** [comment]
It must be an Apollo thing (intentional or not) because there's nothing else that would make my component render twice, double checked that. 

That's what I was wondering, 2 renders feels like a waste of main thread  (if synchronous)..

**Comment by nenjamin2405** [comment]
I had the same problem using apollo link state in react native, although I already put the @client tag in every queries and mutations, apollo client still renders twice: with loading = true and with loading = false.
